"""ISO 3166 alpha-2 + canonical country names + cyber-relevant demonyms.

Hand-rolled to avoid new dependency. Demonyms shipped inline for the top
~30 cyber-attribution-relevant nations; remaining 220+ countries match on
canonical name only.

Used by `enrichment.py` to extract every country mention from event text and
emit `country:<CC>` tags. Priority list governs which country becomes the
single `events.country_code` field used by the geo map (first match wins
when multiple cyber-relevant countries are mentioned).
"""

from __future__ import annotations

# Ranked priority for the single events.country_code field. Earlier = higher.
# Map pin uses the highest-priority country mentioned. Other matches still
# emit country:<CC> tags but do not occupy the country_code slot.
COUNTRY_PRIORITY: tuple[str, ...] = (
    "US", "RU", "CN", "KP", "IR", "UA", "GB", "IL", "DE", "FR",
    "JP", "IN", "KR", "TW", "PK", "SY", "BY", "VE", "CU",
)

# Demonyms for cyber-relevant nations. Patterns are injected into the unified
# regex; alternate forms separated by `|`. Already \b-bounded by the consumer.
_DEMONYMS: dict[str, str] = {
    "US": r"United States|U\.S\.A?\.?|USA|American",
    "RU": r"Russia|Russian|Russian Federation",
    "CN": r"China|Chinese|PRC",
    "KP": r"North Korea|DPRK|Democratic People's Republic of Korea|North Korean",
    "IR": r"Iran|Iranian|Islamic Republic of Iran",
    "UA": r"Ukraine|Ukrainian",
    "GB": r"United Kingdom|U\.K\.|UK|British|Britain|England|Scottish|Welsh",
    "IL": r"Israel|Israeli",
    "DE": r"Germany|German",
    "FR": r"France|French",
    "JP": r"Japan|Japanese",
    "IN": r"India|Indian",
    "KR": r"South Korea|ROK|Republic of Korea|South Korean",
    "TW": r"Taiwan|Taiwanese",
    "PK": r"Pakistan|Pakistani",
    "SY": r"Syria|Syrian",
    "BY": r"Belarus|Belarusian|Belarussian",
    "VE": r"Venezuela|Venezuelan",
    "CU": r"Cuba|Cuban",
    "BR": r"Brazil|Brazilian",
    "AU": r"Australia|Australian",
    "CA": r"Canada|Canadian",
    "NL": r"Netherlands|Dutch|Holland",
    "IT": r"Italy|Italian",
    "ES": r"Spain|Spanish",
    "PL": r"Poland|Polish",
    "TR": r"Turkey|Turkish|T\u00fcrkiye",
    "MX": r"Mexico|Mexican",
    "ZA": r"South Africa|South African",
    "EG": r"Egypt|Egyptian",
    "SA": r"Saudi Arabia|Saudi",
    "AE": r"United Arab Emirates|UAE|Emirati",
    "ID": r"Indonesia|Indonesian",
    "TH": r"Thailand|Thai",
    "VN": r"Vietnam|Vietnamese",
    "PH": r"Philippines|Filipino|Philippine",
    "MY": r"Malaysia|Malaysian",
    "SG": r"Singapore|Singaporean",
    "HK": r"Hong Kong",
    "AR": r"Argentina|Argentinian|Argentine",
    "CL": r"Chile|Chilean",
    "CO": r"Colombia|Colombian",
    "PE": r"Peru|Peruvian",
    "NG": r"Nigeria|Nigerian",
    "KE": r"Kenya|Kenyan",
    "ET": r"Ethiopia|Ethiopian",
    "MA": r"Morocco|Moroccan",
    "GR": r"Greece|Greek",
    "PT": r"Portugal|Portuguese",
    "RO": r"Romania|Romanian",
    "CZ": r"Czech Republic|Czechia|Czech",
    "HU": r"Hungary|Hungarian",
    "AT": r"Austria|Austrian",
    "CH": r"Switzerland|Swiss",
    "BE": r"Belgium|Belgian",
    "SE": r"Sweden|Swedish",
    "NO": r"Norway|Norwegian",
    "DK": r"Denmark|Danish",
    "FI": r"Finland|Finnish",
    "IE": r"Ireland|Irish",
    "NZ": r"New Zealand",
    "EE": r"Estonia|Estonian",
    "LV": r"Latvia|Latvian",
    "LT": r"Lithuania|Lithuanian",
    "GE": r"Georgia|Georgian",
    "AM": r"Armenia|Armenian",
    "AZ": r"Azerbaijan|Azerbaijani",
    "KZ": r"Kazakhstan|Kazakh",
    "UZ": r"Uzbekistan|Uzbek",
    "BD": r"Bangladesh|Bangladeshi",
    "LK": r"Sri Lanka|Sri Lankan",
    "MM": r"Myanmar|Burma|Burmese",
    "AF": r"Afghanistan|Afghan",
    "IQ": r"Iraq|Iraqi",
    "JO": r"Jordan|Jordanian",
    "LB": r"Lebanon|Lebanese",
    "PS": r"Palestine|Palestinian",
    "YE": r"Yemen|Yemeni",
    "QA": r"Qatar|Qatari",
    "KW": r"Kuwait|Kuwaiti",
    "BH": r"Bahrain|Bahraini",
    "OM": r"Oman|Omani",
}

# Long tail - canonical name only, no demonym (less cyber-attribution noise).
_NAME_ONLY: dict[str, str] = {
    "AL": r"Albania",
    "AD": r"Andorra",
    "AO": r"Angola",
    "AG": r"Antigua and Barbuda",
    "BS": r"Bahamas",
    "BB": r"Barbados",
    "BZ": r"Belize",
    "BJ": r"Benin",
    "BT": r"Bhutan",
    "BO": r"Bolivia",
    "BA": r"Bosnia and Herzegovina",
    "BW": r"Botswana",
    "BN": r"Brunei",
    "BG": r"Bulgaria",
    "BF": r"Burkina Faso",
    "BI": r"Burundi",
    "CV": r"Cape Verde|Cabo Verde",
    "KH": r"Cambodia",
    "CM": r"Cameroon",
    "CF": r"Central African Republic",
    "TD": r"Chad",
    "KM": r"Comoros",
    "CG": r"Republic of the Congo",
    "CD": r"Democratic Republic of the Congo|DRC",
    "CR": r"Costa Rica",
    "CI": r"Ivory Coast|C\u00f4te d'Ivoire",
    "HR": r"Croatia",
    "CY": r"Cyprus",
    "DJ": r"Djibouti",
    "DM": r"Dominica",
    "DO": r"Dominican Republic",
    "EC": r"Ecuador",
    "SV": r"El Salvador",
    "GQ": r"Equatorial Guinea",
    "ER": r"Eritrea",
    "SZ": r"Eswatini|Swaziland",
    "FJ": r"Fiji",
    "GA": r"Gabon",
    "GM": r"Gambia",
    "GH": r"Ghana",
    "GD": r"Grenada",
    "GT": r"Guatemala",
    "GN": r"Guinea",
    "GW": r"Guinea-Bissau",
    "GY": r"Guyana",
    "HT": r"Haiti",
    "HN": r"Honduras",
    "IS": r"Iceland",
    "JM": r"Jamaica",
    "KI": r"Kiribati",
    "XK": r"Kosovo",
    "KG": r"Kyrgyzstan",
    "LA": r"Laos",
    "LS": r"Lesotho",
    "LR": r"Liberia",
    "LY": r"Libya",
    "LI": r"Liechtenstein",
    "LU": r"Luxembourg",
    "MO": r"Macau|Macao",
    "MG": r"Madagascar",
    "MW": r"Malawi",
    "MV": r"Maldives",
    "ML": r"Mali",
    "MT": r"Malta",
    "MH": r"Marshall Islands",
    "MR": r"Mauritania",
    "MU": r"Mauritius",
    "FM": r"Micronesia",
    "MD": r"Moldova",
    "MC": r"Monaco",
    "MN": r"Mongolia",
    "ME": r"Montenegro",
    "MZ": r"Mozambique",
    "NA": r"Namibia",
    "NR": r"Nauru",
    "NP": r"Nepal",
    "NI": r"Nicaragua",
    "NE": r"Niger",
    "MK": r"North Macedonia",
    "PW": r"Palau",
    "PA": r"Panama",
    "PG": r"Papua New Guinea",
    "PY": r"Paraguay",
    "PR": r"Puerto Rico",
    "RW": r"Rwanda",
    "KN": r"Saint Kitts and Nevis",
    "LC": r"Saint Lucia",
    "VC": r"Saint Vincent and the Grenadines",
    "WS": r"Samoa",
    "SM": r"San Marino",
    "ST": r"S\u00e3o Tom\u00e9 and Pr\u00edncipe",
    "SN": r"Senegal",
    "RS": r"Serbia",
    "SC": r"Seychelles",
    "SL": r"Sierra Leone",
    "SK": r"Slovakia",
    "SI": r"Slovenia",
    "SB": r"Solomon Islands",
    "SO": r"Somalia",
    "SS": r"South Sudan",
    "SD": r"Sudan",
    "SR": r"Suriname",
    "TJ": r"Tajikistan",
    "TZ": r"Tanzania",
    "TL": r"Timor-Leste|East Timor",
    "TG": r"Togo",
    "TO": r"Tonga",
    "TT": r"Trinidad and Tobago",
    "TN": r"Tunisia",
    "TM": r"Turkmenistan",
    "TV": r"Tuvalu",
    "UG": r"Uganda",
    "UY": r"Uruguay",
    "VU": r"Vanuatu",
    "VA": r"Vatican City|Holy See",
    "ZM": r"Zambia",
    "ZW": r"Zimbabwe",
}

# Unified pattern map: code -> compiled regex with \b boundaries.
COUNTRY_PATTERNS: dict[str, str] = {**_DEMONYMS, **_NAME_ONLY}
