/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/system/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Status */
        get: operations["get_status_api_system_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/attack/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh Attack
         * @description Enqueue the ATT&CK bootstrap actor. Returns 202 Accepted.
         *
         *     Unauthenticated in M1 (CONTEXT). M2 adds the auth dependency.
         */
        post: operations["refresh_attack_admin_attack_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/sources/test-connection": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Test Connection
         * @description Synchronous Test Connection probe. Returns 200 regardless of probe
         *     outcome — the ok flag in the body signals success/failure. UI uses
         *     this as informational only.
         */
        post: operations["test_connection_api_admin_sources_test_connection_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sources */
        get: operations["list_sources_api_admin_sources_get"];
        put?: never;
        /** Create Source */
        post: operations["create_source_api_admin_sources_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/sources/{source_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Source */
        get: operations["get_source_api_admin_sources__source_id__get"];
        put?: never;
        post?: never;
        /** Delete Source */
        delete: operations["delete_source_api_admin_sources__source_id__delete"];
        options?: never;
        head?: never;
        /** Update Source */
        patch: operations["update_source_api_admin_sources__source_id__patch"];
        trace?: never;
    };
    "/api/admin/sources/{source_id}/event-count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Event Count */
        get: operations["event_count_api_admin_sources__source_id__event_count_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/source-templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Source Templates
         * @description List pre-configured source templates operators can quick-add.
         */
        get: operations["list_source_templates_api_admin_source_templates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/webhooks/test-send": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Test Webhook Send
         * @description Non-blocking test send.: always HTTP 200; ok flag in body signals result.
         */
        post: operations["test_webhook_send_api_admin_webhooks_test_send_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/webhooks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Webhooks */
        get: operations["list_webhooks_api_admin_webhooks_get"];
        put?: never;
        /** Create Webhook */
        post: operations["create_webhook_api_admin_webhooks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/webhooks/{webhook_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Webhook */
        get: operations["get_webhook_api_admin_webhooks__webhook_id__get"];
        put?: never;
        post?: never;
        /** Delete Webhook */
        delete: operations["delete_webhook_api_admin_webhooks__webhook_id__delete"];
        options?: never;
        head?: never;
        /** Update Webhook */
        patch: operations["update_webhook_api_admin_webhooks__webhook_id__patch"];
        trace?: never;
    };
    "/api/admin/webhooks/{webhook_id}/reset-cursor": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Reset Cursor
         * @description : reset last_dispatch_at to NULL. Next tick uses 24h lookback.
         */
        put: operations["reset_cursor_api_admin_webhooks__webhook_id__reset_cursor_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/rekey-credentials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rekey Credentials */
        post: operations["rekey_credentials_api_admin_rekey_credentials_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Events */
        get: operations["list_events_api_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/{event_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Event */
        get: operations["get_event_api_events__event_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/{event_id}/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Patch Event Tags
         * @description Add/remove free-text tags on an event.
         *
         *     - Input tags are lowercased server-side before validation and storage.
         *     - Any invalid tag (after lowercasing) in add OR remove → 422 (whole request rejected).
         *     - Re-adding an existing tag is a no-op; removing an absent tag is a no-op (idempotent).
         *     - Response: sorted tag array after the operation.
         *     - 404 if event_id not found (visibility not gated in M1 — auth deferred to M2).
         */
        patch: operations["patch_event_tags_api_events__event_id__tags_patch"];
        trace?: never;
    };
    "/api/presets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Presets
         * @description Return all saved filter presets ordered by name.
         */
        get: operations["list_presets_api_presets_get"];
        put?: never;
        /**
         * Create Preset
         * @description Create a new named filter preset.
         *
         *     Returns 409 Conflict if the name already exists.
         *     Name must match ^[a-z0-9_-]{1,64}$ (enforced by Pydantic; DB CHECK is defence-in-depth).
         */
        post: operations["create_preset_api_presets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/presets/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Preset
         * @description Fetch a single preset by name. 404 if not found.
         */
        get: operations["get_preset_api_presets__name__get"];
        /**
         * Upsert Preset
         * @description Upsert a named preset (create if absent, replace query_params if present).
         *
         *     : ON CONFLICT DO UPDATE must explicitly set updated_at = now
         *      because the column default only fires on INSERT, not on UPDATE.
         *      created_at is preserved across updates (not included in SET clause).
         */
        put: operations["upsert_preset_api_presets__name__put"];
        post?: never;
        /**
         * Delete Preset
         * @description Delete a preset by name.
         *
         *     Returns 204 on success, 404 if not found.
         *     response_class=Response avoids FastAPI 204/None body serialisation bug.
         */
        delete: operations["delete_preset_api_presets__name__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/{event_id}/graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Event Graph */
        get: operations["get_event_graph_api_events__event_id__graph_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * BasicAuth
         * @description HTTP Basic authentication — adds Authorization: Basic <base64> header.
         */
        BasicAuth: {
            /**
             * Type
             * @default basic
             * @constant
             */
            type: "basic";
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /**
         * BearerAuth
         * @description Bearer token authentication — adds Authorization: Bearer <token> header.
         */
        BearerAuth: {
            /**
             * Type
             * @default bearer
             * @constant
             */
            type: "bearer";
            /** Token */
            token: string;
        };
        /** CredentialField */
        CredentialField: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Type */
            type: string;
            /**
             * Required
             * @default true
             */
            required: boolean;
            /** Placeholder */
            placeholder?: string | null;
        };
        /** EventCountResponse */
        EventCountResponse: {
            /** Count */
            count: number;
        };
        /**
         * EventDetail
         * @description Full event including raw_stix JSONB — returned by GET /api/events/{id}.
         */
        EventDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Observed At
             * Format: date-time
             */
            observed_at: string;
            /**
             * Fetched At
             * Format: date-time
             */
            fetched_at: string;
            /** Source Id */
            source_id: string | null;
            /** Source Name */
            source_name?: string | null;
            /** Source Type */
            source_type?: ("rss" | "taxii" | "nvd") | null;
            /** Stix Id */
            stix_id: string | null;
            /** Stix Type */
            stix_type: string;
            /** Title */
            title: string | null;
            /** Description */
            description: string | null;
            /** Tlp */
            tlp?: ("clear" | "green" | "amber" | "amber+strict" | "red") | null;
            /** Tags */
            tags?: string[];
            /** Attack Techniques */
            attack_techniques?: string[];
            /** Archived */
            archived: boolean;
            /**
             * Visibility
             * @enum {string}
             */
            visibility: "shared" | "red_only" | "blue_only";
            /** Geo Lat */
            geo_lat?: number | null;
            /** Geo Lon */
            geo_lon?: number | null;
            /** Raw Stix */
            raw_stix?: {
                [key: string]: unknown;
            } | null;
        };
        /** EventItem */
        EventItem: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Observed At
             * Format: date-time
             */
            observed_at: string;
            /**
             * Fetched At
             * Format: date-time
             */
            fetched_at: string;
            /** Source Id */
            source_id: string | null;
            /** Source Name */
            source_name?: string | null;
            /** Source Type */
            source_type?: ("rss" | "taxii" | "nvd") | null;
            /** Stix Id */
            stix_id: string | null;
            /** Stix Type */
            stix_type: string;
            /** Title */
            title: string | null;
            /** Description */
            description: string | null;
            /** Tlp */
            tlp?: ("clear" | "green" | "amber" | "amber+strict" | "red") | null;
            /** Tags */
            tags?: string[];
            /** Attack Techniques */
            attack_techniques?: string[];
            /** Archived */
            archived: boolean;
            /**
             * Visibility
             * @enum {string}
             */
            visibility: "shared" | "red_only" | "blue_only";
            /** Geo Lat */
            geo_lat?: number | null;
            /** Geo Lon */
            geo_lon?: number | null;
        };
        /** EventListResponse */
        EventListResponse: {
            /** Items */
            items: components["schemas"]["EventItem"][];
            /** Next Cursor */
            next_cursor: string | null;
            /** Total */
            total: number | null;
        };
        /** FilterPresetResponse */
        FilterPresetResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Query Params */
            query_params: {
                [key: string]: unknown;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** GraphEdge */
        GraphEdge: {
            data: components["schemas"]["GraphEdgeData"];
        };
        /** GraphEdgeData */
        GraphEdgeData: {
            /** Source */
            source: string;
            /** Target */
            target: string;
            /** Relation */
            relation: string;
        };
        /** GraphNode */
        GraphNode: {
            data: components["schemas"]["GraphNodeData"];
        };
        /** GraphNodeData */
        GraphNodeData: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Type */
            type: string;
            /** Tag Source */
            tag_source?: string | null;
        };
        /** GraphResponse */
        GraphResponse: {
            /** Nodes */
            nodes: components["schemas"]["GraphNode"][];
            /** Edges */
            edges: components["schemas"]["GraphEdge"][];
            /**
             * Truncated
             * @default false
             */
            truncated: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HeaderAuth
         * @description Arbitrary custom header authentication — adds {name}: {value} header.
         */
        HeaderAuth: {
            /**
             * Type
             * @default header
             * @constant
             */
            type: "header";
            /** Name */
            name: string;
            /** Value */
            value: string;
        };
        /** HealthzResponse */
        HealthzResponse: {
            /** Status */
            status: string;
        };
        /** PresetCreate */
        PresetCreate: {
            /** Name */
            name: string;
            /** Query Params */
            query_params: {
                [key: string]: unknown;
            };
        };
        /** PresetUpsert */
        PresetUpsert: {
            /** Query Params */
            query_params: {
                [key: string]: unknown;
            };
        };
        /** RefreshResponse */
        RefreshResponse: {
            /** Enqueued */
            enqueued: boolean;
            /** Message Id */
            message_id: string | null;
        };
        /** RekeyErrorDetail */
        RekeyErrorDetail: {
            /** Error */
            error: string;
            /** Source Ids */
            source_ids: string[];
        };
        /** RekeyResponse */
        RekeyResponse: {
            /** Rekeyed */
            rekeyed: number;
            /** Skipped */
            skipped: number;
        };
        /** SourceCreate */
        SourceCreate: {
            /** Name */
            name: string;
            /**
             * Feed Type
             * @enum {string}
             */
            feed_type: "rss" | "taxii" | "nvd";
            /** Url */
            url: string;
            /** Credentials */
            credentials?: {
                [key: string]: unknown;
            } | null;
            /** Poll Interval Sec */
            poll_interval_sec: number;
            /** Hot Retention Days */
            hot_retention_days: number;
            /**
             * Archive Policy
             * @default drop
             * @enum {string}
             */
            archive_policy: "keep" | "drop" | "move-to-cold";
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
        };
        /** SourceResponse */
        SourceResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /**
             * Feed Type
             * @enum {string}
             */
            feed_type: "rss" | "taxii" | "nvd";
            /** Url */
            url: string;
            /** Poll Interval Sec */
            poll_interval_sec: number;
            /** Hot Retention Days */
            hot_retention_days: number;
            /**
             * Archive Policy
             * @enum {string}
             */
            archive_policy: "keep" | "drop" | "move-to-cold";
            /** Enabled */
            enabled: boolean;
            /** Last Polled At */
            last_polled_at: string | null;
            /** Last Status */
            last_status: string | null;
            /** Consecutive Failures */
            consecutive_failures: number;
            /** Silent Failure Count */
            silent_failure_count: number;
            /** Effective Status */
            effective_status: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** SourceTemplate */
        SourceTemplate: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Feed Type */
            feed_type: string;
            /** Url */
            url: string;
            /** Description */
            description: string;
            /** Auth Scheme */
            auth_scheme?: string | null;
            /**
             * Credential Fields
             * @default []
             */
            credential_fields: components["schemas"]["CredentialField"][];
            /**
             * Poll Interval Sec
             * @default 3600
             */
            poll_interval_sec: number;
            /** Docs Url */
            docs_url?: string | null;
        };
        /** SourceUpdate */
        SourceUpdate: {
            /** Name */
            name?: string | null;
            /** Url */
            url?: string | null;
            /** Credentials */
            credentials?: {
                [key: string]: unknown;
            } | null;
            /** Poll Interval Sec */
            poll_interval_sec?: number | null;
            /** Hot Retention Days */
            hot_retention_days?: number | null;
            /** Archive Policy */
            archive_policy?: ("keep" | "drop" | "move-to-cold") | null;
            /** Enabled */
            enabled?: boolean | null;
        };
        /** SystemStatusResponse */
        SystemStatusResponse: {
            /** Auth Enabled */
            auth_enabled: boolean;
            /** Host */
            host: string;
            /** Host Loopback Only */
            host_loopback_only: boolean;
            /** Version */
            version: string;
            /** Warning */
            warning: string | null;
            /**
             * Decrypt Check
             * @default unknown
             * @enum {string}
             */
            decrypt_check: "ok" | "failed" | "unknown";
        };
        /** TagPatchRequest */
        TagPatchRequest: {
            /**
             * Add
             * @default []
             */
            add: string[];
            /**
             * Remove
             * @default []
             */
            remove: string[];
        };
        /** TagPatchResponse */
        TagPatchResponse: {
            /** Tags */
            tags: string[];
        };
        /** TestConnectionRequest */
        TestConnectionRequest: {
            /**
             * Feed Type
             * @enum {string}
             */
            feed_type: "rss" | "taxii" | "nvd";
            /** Url */
            url: string;
            /** Credentials */
            credentials?: {
                [key: string]: unknown;
            } | null;
        };
        /** TestConnectionResponse */
        TestConnectionResponse: {
            /** Ok */
            ok: boolean;
            /** Latency Ms */
            latency_ms: number;
            /** Item Count Sampled */
            item_count_sampled: number;
            /** Error Detail */
            error_detail: string | null;
        };
        /**
         * TestSendRequest
         * @description Payload for the test-send endpoint.
         *
         *     Client sends plaintext auth — backend encrypts for the round-trip.
         *     Always returns HTTP 200; ok flag signals success/failure.
         */
        TestSendRequest: {
            /**
             * Destination Type
             * @enum {string}
             */
            destination_type: "slack" | "teams" | "discord" | "generic";
            /** Url */
            url: string;
            /** Auth */
            auth?: components["schemas"]["BearerAuth"] | components["schemas"]["BasicAuth"] | components["schemas"]["HeaderAuth"] | null;
        };
        /**
         * TestSendResponse
         * @description Result of a test-send. HTTP 200 always; ok=False means delivery failed.
         */
        TestSendResponse: {
            /** Ok */
            ok: boolean;
            /** Latency Ms */
            latency_ms: number;
            /** Error Detail */
            error_detail?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * WebhookCreate
         * @description Payload to create a new webhook destination. (HOOK-01)
         */
        WebhookCreate: {
            /** Name */
            name: string;
            /**
             * Destination Type
             * @enum {string}
             */
            destination_type: "slack" | "teams" | "discord" | "generic";
            /** Url */
            url: string;
            /** Auth */
            auth?: components["schemas"]["BearerAuth"] | components["schemas"]["BasicAuth"] | components["schemas"]["HeaderAuth"] | null;
            /**
             * Batching Window Sec
             * @default 300
             */
            batching_window_sec: number;
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /** Bound Preset Names */
            bound_preset_names?: string[];
        };
        /**
         * WebhookResponse
         * @description Webhook representation returned by CRUD endpoints.
         *
         *     auth_enc DELIBERATELY ABSENT — SRC-04 parallel: credentials never returned
         *     in plaintext responses. bound_preset_names populated via join query in router
         *     (07-04); defaults to [] for schema-level tests.
         */
        WebhookResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /**
             * Destination Type
             * @enum {string}
             */
            destination_type: "slack" | "teams" | "discord" | "generic";
            /** Url */
            url: string;
            /** Batching Window Sec */
            batching_window_sec: number;
            /** Enabled */
            enabled: boolean;
            /** Last Dispatch At */
            last_dispatch_at: string | null;
            /** Last Delivery At */
            last_delivery_at: string | null;
            /** Last Delivery Status */
            last_delivery_status: string | null;
            /** Consecutive Failures */
            consecutive_failures: number;
            /** Bound Preset Names */
            bound_preset_names?: string[];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * WebhookUpdate
         * @description Payload to partially update a webhook.
         *
         *     destination_type DELIBERATELY ABSENT — locked on edit.
         */
        WebhookUpdate: {
            /** Name */
            name?: string | null;
            /** Url */
            url?: string | null;
            /** Auth */
            auth?: components["schemas"]["BearerAuth"] | components["schemas"]["BasicAuth"] | components["schemas"]["HeaderAuth"] | null;
            /**
             * Clear Auth
             * @default false
             */
            clear_auth: boolean;
            /** Batching Window Sec */
            batching_window_sec?: number | null;
            /** Enabled */
            enabled?: boolean | null;
            /** Bound Preset Names */
            bound_preset_names?: string[] | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthzResponse"];
                };
            };
        };
    };
    get_status_api_system_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemStatusResponse"];
                };
            };
        };
    };
    refresh_attack_admin_attack_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefreshResponse"];
                };
            };
        };
    };
    test_connection_api_admin_sources_test_connection_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TestConnectionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestConnectionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sources_api_admin_sources_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceResponse"][];
                };
            };
        };
    };
    create_source_api_admin_sources_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SourceCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_source_api_admin_sources__source_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_source_api_admin_sources__source_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_source_api_admin_sources__source_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SourceUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    event_count_api_admin_sources__source_id__event_count_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventCountResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_source_templates_api_admin_source_templates_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceTemplate"][];
                };
            };
        };
    };
    test_webhook_send_api_admin_webhooks_test_send_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TestSendRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestSendResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_webhooks_api_admin_webhooks_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookResponse"][];
                };
            };
        };
    };
    create_webhook_api_admin_webhooks_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WebhookCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_webhook_api_admin_webhooks__webhook_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                webhook_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_webhook_api_admin_webhooks__webhook_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                webhook_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_webhook_api_admin_webhooks__webhook_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                webhook_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WebhookUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_cursor_api_admin_webhooks__webhook_id__reset_cursor_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                webhook_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rekey_credentials_api_admin_rekey_credentials_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Setup-Token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RekeyResponse"];
                };
            };
            /** @description REKEY_FROM_SECRET env var not set */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid or missing X-Setup-Token */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description One or more rows failed to decrypt under REKEY_FROM_SECRET */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RekeyErrorDetail"];
                };
            };
        };
    };
    list_events_api_events_get: {
        parameters: {
            query?: {
                source?: string[] | null;
                source_type?: ("rss" | "taxii" | "nvd")[] | null;
                observed_from?: string | null;
                observed_to?: string | null;
                tlp?: ("clear" | "green" | "amber" | "amber+strict" | "red")[] | null;
                attack_technique?: string[] | null;
                tag?: string[] | null;
                free_text?: string | null;
                include_archived?: boolean;
                has_geo?: boolean;
                tag_mode?: "any" | "all";
                include_total?: boolean;
                cursor?: string | null;
                limit?: number;
            };
            header?: {
                "X-Dashboard-Role"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_event_api_events__event_id__get: {
        parameters: {
            query?: never;
            header?: {
                "X-Dashboard-Role"?: string | null;
            };
            path: {
                event_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_event_tags_api_events__event_id__tags_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TagPatchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagPatchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_presets_api_presets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FilterPresetResponse"][];
                };
            };
        };
    };
    create_preset_api_presets_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PresetCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FilterPresetResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_preset_api_presets__name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FilterPresetResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upsert_preset_api_presets__name__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PresetUpsert"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FilterPresetResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_preset_api_presets__name__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_event_graph_api_events__event_id__graph_get: {
        parameters: {
            query?: {
                depth?: number;
            };
            header?: {
                "X-Dashboard-Role"?: string | null;
            };
            path: {
                event_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
